-- Phase 5 — Clinical notes with versioning and AI generation tracking.
--
-- Clinical notes are versioned (PRD §23): v1 = AI generated, v2 = doctor
-- edited, v3 = doctor approved. Approved records are never silently
-- overwritten; any modification creates a new version.
--
-- AI-generated content is always a draft until a clinician approves it
-- (PRD §5, §12). The original transcript is never overwritten by AI output
-- (PRD §4).
--
-- Idempotent: safe to re-run.


-- ===========================================================================
-- Enums
-- ===========================================================================

do $$
begin
  if not exists (select 1 from pg_type where typname = 'note_status') then
    create type public.note_status as enum (
      'draft',      -- AI-generated, awaiting doctor review
      'in_review',  -- doctor is editing
      'approved',   -- doctor has approved; this is an official record
      'rejected'    -- doctor rejected the AI draft
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'note_version_source') then
    create type public.note_version_source as enum (
      'ai_generated',  -- generated by the AI pipeline
      'doctor_edited', -- edited by a clinician
      'doctor_approved' -- approved by a clinician (final)
    );
  end if;
end
$$;


-- ===========================================================================
-- Tables
-- ===========================================================================

-- A clinical note for a consultation. The "current" version is the latest
-- row in clinical_note_versions for this note. The note itself is a container;
-- the content lives in the versions table so the full edit history is
-- preserved (PRD §23).
create table if not exists public.clinical_notes (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations (id)
    on delete cascade,
  consultation_id uuid not null references public.consultations (id)
    on delete cascade,
  patient_id uuid not null references public.patients (id) on delete cascade,
  -- The current status of the note. 'approved' means it is an official
  -- clinical record.
  status public.note_status not null default 'draft',
  -- The current version number. Incremented on each new version.
  current_version int not null default 1,
  -- Who approved the note, if anyone. Only clinicians may approve
  -- (PRD §5: CLINICAL_NOTE_APPROVE permission).
  approved_by uuid references auth.users (id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.clinical_notes is
  'A clinical note for a consultation. Versioned via clinical_note_versions (PRD §23).';
comment on column public.clinical_notes.status is
  'draft = AI-generated, awaiting review; approved = official record (PRD §5).';


-- The versioned content of a clinical note. Each row is an immutable snapshot
-- of the note at a point in time. The latest row (by version number) is the
-- current content.
create table if not exists public.clinical_note_versions (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations (id)
    on delete cascade,
  clinical_note_id uuid not null references public.clinical_notes (id)
    on delete cascade,
  version int not null,
  source public.note_version_source not null,
  -- The SOAP note content. Structured per PRD §5.
  subjective text,
  objective text,
  assessment text,
  plan text,
  follow_up text,
  -- The doctor who created or edited this version.
  authored_by uuid not null references auth.users (id) on delete set null,
  -- Free-text edit note, e.g. "corrected dosage in plan".
  edit_note text,
  created_at timestamptz not null default now()
);

comment on table public.clinical_note_versions is
  'Immutable versioned content of a clinical note (PRD §23).';
comment on column public.clinical_note_versions.source is
  'ai_generated, doctor_edited, or doctor_approved (PRD §23).';


-- AI generation records. Tracks every AI call so we have an audit trail of
-- what was generated, from what source, and with what model. Never stores
-- the full prompt or response (those may be large); stores metadata only.
create table if not exists public.ai_generations (
  id uuid primary key default extensions.gen_random_uuid(),
  organization_id uuid not null references public.organizations (id)
    on delete cascade,
  consultation_id uuid references public.consultations (id) on delete cascade,
  clinical_note_id uuid references public.clinical_notes (id) on delete set null,
  -- The type of AI task: transcription, soap_generation, etc.
  task_type text not null,
  -- The provider used: openai, etc.
  provider text not null,
  -- The model identifier, e.g. "gpt-4o", "whisper-1".
  model text,
  -- The status of the generation: pending, completed, failed.
  status text not null default 'pending',
  -- Error message if failed. Identifiers only, never clinical content.
  error_message text,
  -- Duration in milliseconds.
  duration_ms int,
  created_at timestamptz not null default now()
);

comment on table public.ai_generations is
  'Audit trail of AI generation calls. Metadata only, never clinical content.';


-- ===========================================================================
-- Indexes
-- ===========================================================================

create index if not exists clinical_notes_consultation_idx
  on public.clinical_notes (consultation_id);
create index if not exists clinical_notes_patient_idx
  on public.clinical_notes (patient_id, created_at desc);
create index if not exists clinical_notes_organization_status_idx
  on public.clinical_notes (organization_id, status);

create index if not exists clinical_note_versions_note_idx
  on public.clinical_note_versions (clinical_note_id, version desc);

create index if not exists ai_generations_consultation_idx
  on public.ai_generations (consultation_id, created_at desc);


-- ===========================================================================
-- Authorization helpers
-- ===========================================================================

create or replace function public.is_note_org_member(note_id uuid)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.clinical_notes n
    join public.organization_members m
      on m.organization_id = n.organization_id
    where n.id = note_id
      and m.user_id = auth.uid()
      and m.status = 'active'
  );
$$;

comment on function public.is_note_org_member(uuid) is
  'True when the current user is an active member of the note''s organization.';


-- ===========================================================================
-- Triggers
-- ===========================================================================

drop trigger if exists clinical_notes_set_updated_at on public.clinical_notes;
create trigger clinical_notes_set_updated_at
  before update on public.clinical_notes
  for each row execute function public.set_updated_at();


-- When a clinical note is approved, add a timeline event.
create or replace function public.add_note_timeline_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status = 'approved' and (old.status is null or old.status <> 'approved') then
    insert into public.patient_timeline_events
      (patient_id, organization_id, event_type, event_date, title, description,
       source_type, source_id)
    values
      (new.patient_id, new.organization_id, 'consultation',
       coalesce(new.approved_at::date, current_date),
       'Clinical note approved',
       coalesce('Version: ' || new.current_version::text, null),
       'clinical_notes', new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists clinical_notes_timeline on public.clinical_notes;
create trigger clinical_notes_timeline
  after update of status on public.clinical_notes
  for each row execute function public.add_note_timeline_event();


-- ===========================================================================
-- Row Level Security
-- ===========================================================================

alter table public.clinical_notes          enable row level security;
alter table public.clinical_note_versions  enable row level security;
alter table public.ai_generations          enable row level security;


-- --- clinical_notes ---------------------------------------------------------

drop policy if exists clinical_notes_select_members on public.clinical_notes;
create policy clinical_notes_select_members
  on public.clinical_notes for select
  to authenticated
  using (public.is_org_member(organization_id));

drop policy if exists clinical_notes_insert_members on public.clinical_notes;
create policy clinical_notes_insert_members
  on public.clinical_notes for insert
  to authenticated
  with check (public.is_org_member(organization_id));

drop policy if exists clinical_notes_update_members on public.clinical_notes;
create policy clinical_notes_update_members
  on public.clinical_notes for update
  to authenticated
  using (public.is_org_member(organization_id))
  with check (public.is_org_member(organization_id));

-- No DELETE: clinical notes are never deleted. An approved note is an
-- official clinical record (PRD §23).


-- --- clinical_note_versions -------------------------------------------------

drop policy if exists clinical_note_versions_select_members on public.clinical_note_versions;
create policy clinical_note_versions_select_members
  on public.clinical_note_versions for select
  to authenticated
  using (public.is_org_member(organization_id));

drop policy if exists clinical_note_versions_insert_members on public.clinical_note_versions;
create policy clinical_note_versions_insert_members
  on public.clinical_note_versions for insert
  to authenticated
  with check (public.is_org_member(organization_id));

-- No UPDATE or DELETE: versions are immutable (PRD §23).


-- --- ai_generations ---------------------------------------------------------

-- AI generation records are read-only from the client's perspective.
drop policy if exists ai_generations_select_members on public.ai_generations;
create policy ai_generations_select_members
  on public.ai_generations for select
  to authenticated
  using (public.is_org_member(organization_id));

-- No INSERT, UPDATE, or DELETE for authenticated: written by the backend
-- with the service role.


-- ===========================================================================
-- Grants
-- ===========================================================================

revoke all on public.clinical_notes         from anon;
revoke all on public.clinical_note_versions from anon;
revoke all on public.ai_generations         from anon;

grant select, insert, update on public.clinical_notes         to authenticated;
grant select, insert         on public.clinical_note_versions to authenticated;
grant select                 on public.ai_generations         to authenticated;
